name: Release
on:
  push:
    branches:
      - "!**/*"
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v1
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v1

    - name: setup tools
      run: |
        go get -v github.com/mitchellh/gox@v1.0.1
        curl -sL https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar zxvf - && install ghr_v0.13.0_linux_amd64/ghr ~/go/bin/
    - name: packages
      run: PATH=~/go/bin:$PATH make packages
      env:
        CGO_ENABLED: 0

    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: PATH=~/go/bin:$PATH make release
